/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAccountDialog: typeof import('./src/components/admin/account/AdminAccountDialog.vue')['default']
    AdminAccountEditForm: typeof import('./src/components/admin/account/AdminAccountEditForm.vue')['default']
    AdminAccountForm: typeof import('./src/components/admin/account/AdminAccountForm.vue')['default']
    AdminAccountHeader: typeof import('./src/components/admin/account/AdminAccountHeader.vue')['default']
    AdminAccountTable: typeof import('./src/components/admin/account/AdminAccountTable.vue')['default']
    AdminHeader: typeof import('./src/components/admin/AdminHeader.vue')['default']
    AdminSideMenu: typeof import('./src/components/admin/AdminSideMenu.vue')['default']
    AdminWebInfoForm: typeof import('./src/components/admin/web-info/AdminWebInfoForm.vue')['default']
    AdminWebInfoLogoUpload: typeof import('./src/components/admin/web-info/AdminWebInfoLogoUpload.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LogoTitlePart: typeof import('./src/components/LogoTitlePart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./src/components/sign/SignInForm.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
