/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAccountDialog: typeof import('./src/components/admin/account/AdminAccountDialog.vue')['default']
    AdminAccountEditForm: typeof import('./src/components/admin/account/AdminAccountEditForm.vue')['default']
    AdminAccountForm: typeof import('./src/components/admin/account/AdminAccountForm.vue')['default']
    AdminAccountHeader: typeof import('./src/components/admin/account/AdminAccountHeader.vue')['default']
    AdminAccountTable: typeof import('./src/components/admin/account/AdminAccountTable.vue')['default']
    AdminAiModelDialog: typeof import('./src/components/admin/ai-model/AdminAiModelDialog.vue')['default']
    AdminAiModelDrawer: typeof import('./src/components/admin/ai-model/AdminAiModelDrawer.vue')['default']
    AdminAiModelForm: typeof import('./src/components/admin/ai-model/AdminAiModelForm.vue')['default']
    AdminAiModelHeader: typeof import('./src/components/admin/ai-model/AdminAiModelHeader.vue')['default']
    AdminAiModelTable: typeof import('./src/components/admin/ai-model/AdminAiModelTable.vue')['default']
    AdminAiProviderDialog: typeof import('./src/components/admin/ai-provider/AdminAiProviderDialog.vue')['default']
    AdminAiProviderEditForm: typeof import('./src/components/admin/ai-provider/AdminAiProviderEditForm.vue')['default']
    AdminAiProviderForm: typeof import('./src/components/admin/ai-provider/AdminAiProviderForm.vue')['default']
    AdminAiProviderHeader: typeof import('./src/components/admin/ai-provider/AdminAiProviderHeader.vue')['default']
    AdminAiProviderTable: typeof import('./src/components/admin/ai-provider/AdminAiProviderTable.vue')['default']
    AdminHeader: typeof import('./src/components/admin/AdminHeader.vue')['default']
    AdminSideMenu: typeof import('./src/components/admin/AdminSideMenu.vue')['default']
    AdminWebInfoForm: typeof import('./src/components/admin/web-info/AdminWebInfoForm.vue')['default']
    AdminWebInfoLogoUpload: typeof import('./src/components/admin/web-info/AdminWebInfoLogoUpload.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    LogoTitlePart: typeof import('./src/components/LogoTitlePart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./src/components/sign/SignInForm.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
